global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "bilbopass-api"
    static_configs:
      - targets: ["api:8080"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "nats"
    static_configs:
      - targets: ["nats:8222"]
    metrics_path: /varz
    scrape_interval: 30s
